import { ItemData } from '../typings/item';

export const Items: {
  [key: string]: ItemData | undefined;
} = {
  water: {
    name: 'water',
    close: false,
    label: 'Water Bottle',
    stack: true,
    usable: true,
    count: 0,
  },
  burger: {
    name: 'burger',
    close: false,
    label: 'Burger',
    stack: true,
    usable: true,
    count: 0,
  },
  iron: {
    name: 'iron',
    close: false,
    label: 'Iron Ingot',
    stack: true,
    usable: false,
    count: 0,
    description: 'A refined iron ingot used for crafting.',
  },
  copper: {
    name: 'copper',
    close: false,
    label: 'Copper Wire',
    stack: true,
    usable: false,
    count: 0,
    description: 'Thin copper wire used in electronics.',
  },
  powersaw: {
    name: 'powersaw',
    close: false,
    label: 'Power Saw',
    stack: false,
    usable: true,
    count: 0,
    description: 'A portable power saw for cutting materials.',
  },
  lockpick: {
    name: 'lockpick',
    close: true,
    label: 'Lockpick',
    stack: true,
    usable: true,
    count: 0,
    description: 'Simple lockpick that breaks easily and can pick basic door locks.',
  },
  bandage: {
    name: 'bandage',
    close: true,
    label: 'Bandage',
    stack: true,
    usable: true,
    count: 0,
    description: 'A medical bandage to stop bleeding.',
  },
  radio: {
    name: 'radio',
    close: false,
    label: 'Radio',
    stack: false,
    usable: true,
    count: 0,
    description: 'A handheld two-way radio.',
  },
  phone: {
    name: 'phone',
    close: false,
    label: 'Phone',
    stack: false,
    usable: true,
    count: 0,
    description: 'Your personal mobile phone.',
  },
  pistol: {
    name: 'pistol',
    close: false,
    label: 'Pistol',
    stack: false,
    usable: true,
    count: 0,
    description: 'A standard issue 9mm pistol.',
    ammoName: 'ammo-9',
  },
  'ammo-9': {
    name: 'ammo-9',
    close: false,
    label: '9mm Ammo',
    stack: true,
    usable: false,
    count: 0,
    description: 'Standard 9mm ammunition.',
  },
  vest: {
    name: 'vest',
    close: false,
    label: 'Body Armor',
    stack: false,
    usable: true,
    count: 0,
    description: 'Level II body armor vest.',
  },
  backwoods: {
    name: 'backwoods',
    close: false,
    label: 'Backwoods',
    stack: true,
    usable: true,
    count: 0,
  },
  medkit: {
    name: 'medkit',
    close: true,
    label: 'Medical Kit',
    stack: true,
    usable: true,
    count: 0,
    description: 'A comprehensive medical kit for treating injuries.',
  },
  flashlight: {
    name: 'flashlight',
    close: false,
    label: 'Flashlight',
    stack: false,
    usable: true,
    count: 0,
    description: 'A high-powered LED flashlight.',
  },
  screwdriver: {
    name: 'screwdriver',
    close: false,
    label: 'Screwdriver',
    stack: false,
    usable: true,
    count: 0,
    description: 'A flathead screwdriver.',
  },
  rope: {
    name: 'rope',
    close: false,
    label: 'Rope',
    stack: true,
    usable: false,
    count: 0,
    description: 'A length of strong nylon rope.',
  },
  sandwich: {
    name: 'sandwich',
    close: true,
    label: 'Sandwich',
    stack: true,
    usable: true,
    count: 0,
    description: 'A delicious sandwich.',
  },
  soda: {
    name: 'soda',
    close: true,
    label: 'Soda Can',
    stack: true,
    usable: true,
    count: 0,
    description: 'A refreshing carbonated drink.',
  },
};
